### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by lendicott** [GridProtectionAlliance/PQDashboard#12]
does anyone know how to fix this?
![image](https://user-images.githubusercontent.com/51378855/58898904-a23d8500-86c9-11e9-9878-6cd7ad3105e4.png)

**Comment by StephenCWills** [comment]
The details about the error are being hidden for security reasons. You will need to run a web browser on the web server or else modify the Web.config as described on that page to see the actual message for the error you are receiving.

**Comment by lendicott** [comment]
![image](https://user-images.githubusercontent.com/51378855/58909291-b6d94780-86e0-11e9-9a49-f0072aefe58f.png)

**Comment by StephenCWills** [comment]
That looks like an error I've gotten after upgrading between versions, usually resulting from an oversight in the database upgrade script.

1. Did you upgrade the system that is now having this issue?
2. Does your DeviceFilter table define a field called MeterGroupID? If so, it should be renamed to AssetGroupID.

**Comment by lendicott** [comment]
Do I need to upgrade OpenXDA or revert the system back?
